// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


const ARGS_MAP = { 'seshat':'{"supports_event_indexing":[],"init_event_index":["passphrase"]}' }
export type Router = { 'seshat': { supports_event_indexing: () => Promise<boolean>, 
init_event_index: (passphrase: string) => Promise<void> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
