## Normally the script fetch-package should install the deps etc but it is not working on the CI :/
name: Build Webapp

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      env:
        required: true
        type: string
        default: prod

jobs:
  build-webapp:
    runs-on: ubuntu-latest

    outputs:
      build_success: ${{ steps.build-result.outputs.success }}

    steps:
      - uses: actions/checkout@v4

      # Add step to determine Node.js version
      - name: Determine Node.js version
        id: nodever
        run: |
          NODE_VERSION="lts/*"
          if [ -f "package.json" ]; then
            if [ "$(jq -r '.tchapConfig.use_github // false' package.json)" = "true" ]; then
              NODE_VERSION="22.18.0"
            fi
          fi
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodever.outputs.NODE_VERSION }}

      # Add step to check package.json configuration
      - name: Check build type (archive or github)
        id: build-type
        shell: bash
        run: |
          if [ "$(jq -r --arg env "$ENV" '.tchapConfig[$env].use_github // false' package.json)" = "true" ]; then
            echo "BUILD_TYPE=github" >> $GITHUB_OUTPUT
          else
            echo "BUILD_TYPE=package" >> $GITHUB_OUTPUT
          fi
        env:
          ENV: ${{ inputs.env }}

      # Install dependencies based on build type
      - name: Install dependencies (Package)
        # if: steps.build-type.outputs.BUILD_TYPE == 'package'
        shell: bash
        run: |
          npm i -g pnpm
          npm install
          echo "ENV is: $ENV"
          npm run fetch-package -- "$ENV"
        env:
          ENV: ${{ inputs.env }}

      # To share the result of the build with another workflow, we need to upload the webapp as an artifact
      - name: Upload webapp as artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true # Means that another platform already uploaded the artifact, so we don't need to fail the build
        with:
          name: webapp_${{ github.run_id }}_${{ inputs.env }}
          path: src/
